att_dict = {
'airplane' : ['small', 'cloudy', 'concrete'], 
'ax' : ['baseball'], 
'baby' : ['wooden', 'wood', 'long'], 
'back pack' : ['young'], 
'bag' : ['parked', 'sleeping', 'resting', 'sitting', 'standing'], 
'bamboo' : ['calm'], 
'banner' : ['sitting', 'standing'], 
'bed' : ['sleeping', 'sitting'], 
'bicycle' : ['riding'], 
'billboard' : ['parked', 'tall'], 
'bin' : ['parked'], 
'blanket' : ['sleeping', 'cooked'], 
'boat' : ['watching', 'cement', 'walking', 'paved', 'docked', 'flying', 'leather', 'concrete', 'stone', 'sitting', 'standing', 'driving', 'swimming', 'smiling', 'looking'], 
'bottle' : ['parked', 'stone', 'paper', 'tall', 'sitting', 'wii'], 
'bowl' : ['shiny', 'paper'], 
'box' : ['computer', 'parked', 'sitting', 'straw', 'tall'], 
'boy' : ['wooden', 'old'], 
'branch' : ['cement', 'walking', 'paved', 'concrete', 'stone', 'standing', 'metal'], 
'broom' : ['walking', 'young'], 
'bucket' : ['tall', 'sitting'], 
'building' : ['watching', 'parked', 'sitting', 'walking', 'leafless', 'cloudy', 'flying', 'moving', 'leafy', 'standing', 'wii', 'lit', 'calm', 'docked', 'growing', 'bare'], 
'bush' : ['parked', 'metal'], 
'cage' : ['parked', 'tall', 'long', 'large'], 
'camera' : ['sitting', 'standing'], 
'canopy' : ['cloudy', 'parked'], 
'car' : ['off', 'wooden', 'piled', 'shiny', 'tall', 'paved', 'lit', 'shining', 'sitting', 'street', 'watching', 'concrete', 'docked', 'wood', 'old', 'leather', 'hanging', 'standing', 'calm', 'walking', 'asphalt', 'driving'], 
'cart' : ['sitting', 'standing', 'young'], 
'ceiling fan' : ['flying', 'sitting'], 
'chair' : ['open', 'sitting'], 
'clothes' : ['sitting', 'standing'], 
'debris' : ['bald', 'calm', 'docked', 'eating', 'sleeping', 'parked', 'tall', 'sitting', 'standing', 'young', 'smiling'], 
'dog' : ['wooden', 'metal'], 
'dolphin' : ['wooden', 'denim', 'wood', 'sitting'], 
'dress' : ['sitting'], 
'excavator' : ['wooden'], 
'factory' : ['parked'], 
'fence' : ['calm', 'parked', 'sitting', 'smiling'], 
'field' : ['tall'], 
'fire' : ['cloudy', 'slice', 'tall', 'sliced', 'chocolate', 'hanging', 'metal'], 
'fire hydrant' : ['sitting', 'swimming'], 
'fish' : ['metal'], 
'fishing rod' : ['calm'], 
'flag' : ['wooden', 'tall', 'flying', 'metal', 'standing', 'sitting'], 
'floor' : ['sitting'], 
'girl' : ['flying'], 
'glass' : ['rocky'], 
'grass' : ['calm', 'cement', 'tiled', 'asphalt', 'parked', 'concrete', 'metal', 'brick', 'paved'], 
'gun' : ['ski'], 
'helicopter' : ['daytime', 'cloudy', 'sitting', 'swimming'], 
'kitchen' : ['sitting', 'standing'], 
'ladder' : ['tall', 'glass'], 
'lantern' : ['sitting'], 
'license plate' : ['open'], 
'life jacket' : ['sitting'], 
'light' : ['metal'], 
'log' : ['calm', 'concrete', 'metal'], 
'mailbox' : ['walking', 'baseball', 'swimming'], 
'man' : ['concrete', 'wooden', 'parked', 'stone', 'large', 'metal'], 
'map' : ['standing'], 
'mask' : ['glass'], 
'mattress' : ['concrete', 'stone', 'metal'], 
'motor' : ['walking', 'parked', 'sitting', 'driving', 'young', 'standing'], 
'motorbike' : ['walking', 'riding', 'sitting'], 
'napkin' : ['dead'], 
'paddle' : ['walking', 'holding', 'standing'], 
'people' : ['wrinkled', 'wooden', 'parked', 'rocky', 'iron', 'wood', 'metal'], 
'person' : ['wooden', 'parked', 'stone', 'round', 'open', 'stuffed', 'flying', 'framed', 'arched', 'metal'], 
'pillow' : ['sleeping'], 
'pole' : ['leafless', 'walking', 'flying', 'electrical'], 
'power line' : ['leafy'], 
'reflection' : ['calm', 'cement', 'walking', 'parked', 'concrete', 'stone', 'tall', 'shining', 'standing', 'driving', 'old'], 
'refrigerator' : ['wooden'], 
'road' : ['parked'], 
'rope' : ['metal'], 
'sand' : ['pink'], 
'shadow' : ['cement', 'concrete'], 
'shelf' : ['tall'], 
'shoe' : ['airborne', 'standing', 'up'], 
'shovel' : ['glass'], 
'sidewalk' : ['tall', 'cardboard'], 
'sign' : ['walking', 'parked', 'concrete', 'stone', 'standing', 'lit'], 
'sky' : ['leafless', 'cement', 'concrete', 'stone', 'pink', 'tall', 'metal', 'big', 'brick', 'bright', 'green', 'bare', 'brown', 'red'], 
'smoke' : ['tall', 'big'], 
'spray' : ['tall', 'water'], 
'stick' : ['smiling', 'tall', 'walking', 'standing', 'young'], 
'stroller' : ['smiling', 'sitting', 'young'], 
'styrofoam' : ['wooden'], 
'suitcase' : ['sitting'], 
'supply' : ['concrete', 'sitting'], 
'surveillance camera' : ['sitting', 'walking', 'standing'], 
'suv' : ['walking', 'sitting', 'standing', 'driving'], 
'table' : ['parked', 'sitting'], 
'tank' : ['tall', 'cement', 'concrete'], 
'tape' : ['coffee'], 
'tractor' : ['standing'], 
'traffic light' : ['flying', 'parked', 'sitting', 'lit'], 
'trailer' : ['tall'], 
'trash' : ['sitting', 'concrete'], 
'tree' : ['clear', 'cloudy', 'walking', 'paved', 'wooden', 'flying', 'cooked', 'parked', 'traffic', 'concrete', 'stone', 'striped', 'sitting', 'glass', 'standing', 'young', 'off', 'hanging', 'metal', 'smiling', 'brick', 'lit', 'white', 'blue', 'chain link', 'clear'], 
'trees' : ['clear', 'cloudy', 'wooden', 'electrical', 'parked', 'standing', 'hanging', 'metal', 'overcast', 'brick', 'white', 'blue', 'chain link'], 
'truck' : ['cement', 'wooden', 'docked', 'concrete', 'wearing', 'stone', 'moving', 'sitting', 'wood', 'standing', 'young', 'smiling', 'brick', 'playing'], 
'tube' : ['sitting', 'laying'], 
'umbrella' : ['walking', 'wooden', 'parked', 'sitting', 'wood'], 
'van' : ['wooden', 'leather', 'wood', 'driving'], 
'vehicle' : ['watching', 'walking', 'wooden', 'concrete', 'sitting', 'standing', 'young'], 
'wand' : ['sandy'], 
'water' : ['wooden', 'parked', 'tall', 'sitting', 'old', 'growing', 'tiled', 'dead', 'busy', 'standing', 'painted', 'paved', 'metal', 'chain link'], 
'wave' : ['moving', 'tall'], 
'wheelchair' : ['riding', 'smiling', 'sitting', 'young'], 
'wire' : ['overcast', 'tall', 'cloudy'], 
'woman' : ['wooden', 'long', 'stone', 'open', 'brick'], 
'wood' : ['metal']
}

for key in  att_dict:
    print("\'", end="")
    print(key, end="")
    print("\'", ": ", end="")
    print(sorted(att_dict[key]), end=", \n")

#materials  = ['brick', 'ceramic', 'glass', 'gravel', 'hardwood', 'metal', 'plastic', 'stainless steel', 'wooden']
#print(sorted(materials))



